### ISSUE TITLE
Routing issues

### ISSUE THREAD

**Issue by veiraz** [resir014/NineSevenThree#5]
The docs currently [pulls its stylesheet](https://github.com/resir014/NineSevenThree/blob/f8e55b9b11147ce2dde45c62ed6a093e5aca5825/docs/_layouts/default.html#L11) by getting the `{{ site.baseurl }}` variable from [here](https://github.com/resir014/NineSevenThree/blob/f8e55b9b11147ce2dde45c62ed6a093e5aca5825/_config.yml#L10). This of course translates to something like `/NineSevenThree/css/docs.css`, which would be fine and all except it doesn't exists.

Personally I'm not sure why you need a `base-url` there anyway but I'm not really sure where you're going with this so I can't open a pull request.

**Comment by resir014** [comment]
Not sure if I got your question right, but I was sort-of experimenting with the build system used [here](https://github.com/primer/primer).

For the `baseurl` routing, I grabbed this method from [here](http://jekyllrb.com/docs/github-pages/#project-page-url-structure) on how to structure URLs for GitHub Pages.

On a normal `jekyll` or `grunt publish` task, it will load [here](https://github.com/resir014/NineSevenThree/blob/f8e55b9b11147ce2dde45c62ed6a093e5aca5825/_config.yml#L7) it pulls the `.scss` files out of the `docs` directory and builds it into a Jekyll server, or in case on a `grunt publish` task, it will push the generated files to he `gh-pages` branch.

This, of course, will lead to some problems, specifically when if I want to host the pages the way it should be, without pushing the pages files through `grunt`. I'm currently just experimenting on build systems and see if something sticks.
